---
title: "Workdone for chapter1-3"
author: "Luckson"
date: "11/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# First Part Excerise 2.1
((6*2.3)+42)/(3^(4.2-3.62))
-4^2+2
sqrt(mean(25.2+15+16.44+15.3+18.6))
exp(0.3)
log(x=1.349859)
4.235463e-09
```
# Second Part Excercise 2.2
```{r}
l <- 3^2*4^(1/8)
l

l <- l/2.33
l
l <- -8.2
l
b <- l*10^-13
b
l * b

```
# Third Part Exercise 2.3
```{r}
mandi <- seq (from=5,to=-11,by=-0.3)
mandi

mandi <- seq(from=-11,to=5,by=0.3)
mandi

taf <- rep(x=c(-1,3,-5,7,-9),times=2, each=10)
taf

sortaf <- sort(x=taf,decreasing=TRUE)
sortaf

mandia <-seq(from=6,to=12)
mandia

mandi1 <-rep(x=c (5.3), times=3)
mandi1
b <- (x=-3)
b

mandi2 <- seq(from=102,to=(length((sortaf))),length.out = 9)
mandi2

endworth <- c(mandia,mandi1,b,mandi2)
endworth

length (endworth)
```
# Fourth Part Exercise 2.4
```{r}
srta <- seq(from=3, to=6, length.out = 5)
srta
srtb <- rep (x=c (2,5.2,-33), times= 3)
srtb
y <- ((7/42)+2)
y
startvec <- (x=c(seqa,seqb,y))
startvec
store <- startvec[1]
store
store2 <- startvec[15]
store2
newstore <- (x=c(store,store2))
newstore
nostore2<- startvec [-1][-14]
nostore2
startvec2 <- c(newstore,nostore2)
startvec2
startvec <- sort(x=c(startvec, decreasing =FALSE))
startvec
colonstartvec <- startvec[13:1]
colonstartvec
w <- rep(nostore2[3], times=3)
w
e <- rep(nostore2[6], times=4)
e
f <- rep(nostore2[10], times=1)
f
gvector <-c(w,e,f)
gvector
dostartvec <- startvec
dostartvec
dostartvec [c(1,5,6,7,13)] <- c(99,98,97,96,95)
dostartvec
```
# Fifth Part Exercise 2.5
```{r}
pq<- c(2,0.5,1,2,0.5,1,2,0.5,1)
pq
pq1 <- tq[c(1:9)] <- c(1,1,1,1,1,1,1,1,1)
pq1
cel <- c(5/9*(45-32),5/9*(77-32),5/9*(20-32),5/9*(19-32),5/9*(101-32),5/9*(120-32),5/9*(212-32))
cel
t <- c(2,4,6)*1
t
t2 <- c(1,2)*2
t2
t3 <- c(t2,t)
t3
t3 [c(2,3,4,5)]<- c(-0.1,-100,-0.1,-100)
t3

```
# Sixth Part Exercise 3.1
```{r}
amatrix <- matrix(data=c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5), nrow =4, ncol =2)
amatrix
bmatrix <- amatrix [-1,]
bmatrix
dim(bmatrix)
amatrix[,2] <- c(0.9,1.6,3.2,6.5)
amatrix
cmatrix <- amatrix [-4,-1]
cmatrix
dmatrix <- matrix (data=c(cmatrix))
dmatrix
fmatrix <- amatrix[c(3,4),1:2]
fmatrix

```
# Seventh Part Exercise 3.2
```{r}
b <- matrix (data=c(10,30,50,20,40,60), nrow =3, ncol =2)
b
a <- matrix (data=c(1,2,7,2,4,6), nrow =3, ncol =2)
a
c <- a-b
c
d <- 2/7*c
d
A1 <- matrix (data=c(1,2,7))
A1
B1 <- matrix (data=c(3,4,8))
B1
C1 <- A1*B1
C1
BT <- t(B1)
BT
F <-matrix(data=c(2,0,0,0,0,3,0,0,0,0,5,0,0,0,0,-1), nrow= 4, ncol = 4)
F
F1 <- solve(F)
F1
L <- diag(4)
L
nothing <- F1*F-L
nothing
dim(nothing)
```
# Eighthy Part Exercise 3.3
```{r}
taf <- seq(from=4.8, to=0.1, length.out=8)
taf
taf <- matrix (data=c(4.8,4.1285714,3.4571429,2.7857143,2.1142857,1.4428571,0.7714286,0.1), nrow =4, ncol =2)
taf3
taf4 <- array (data=(taf3),dim=c(4,2,6))
taf4
taf5 <-taf4[4,2,]
taf5
taf6 <-taf4[1,2,]
taf6
taf7 <- matrix(data=c(taf5,taf6))
taf7
taf10 <- array(data=rep(taf7,times=4))
taf10
taf11 <- array(taf10,dim=c(2,2,2,3))
taf11
taf12 <- array (data=(taf3),dim=c(4,2,5))
taf12
taf12[2,2,1] <- -99
taf12[4,2,1] <- -99
taf12[2,2,3] <- -99
taf12[4,2,3] <- -99
taf12[2,2,5] <- -99
taf12[4,2,5] <- -99
taf12
```








